### ISSUE TITLE
Navbar should not be reordered

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#2]
At the moment the navbar is reordered alphabetically automatically - this prevents flexibility in the future and should be removed

**Comment by apple-phi** [comment]
That's not quite the current behaviour and this appears to be a bug. The current intended behaviour is for the headings of `News, Welfare, Services, About` are pushed to the back of the navbar, in that order, with any extra navbar entries left in their original order at the start of the navbar. 

However, the implementation does this by having the initial value of the `$navStore` to be a navbar pre-filled with these expected headings (to minimise UI changes after initial page load) and trusts the CMS to _always_ serve a navbar which has `News, Welfare, Services, About` entries as a subset (at least, if this order is desired to be preserved).

In this case, since the first time your browser opened the website, the navbar was incomplete only had the entry for `Welfare`, so any later navbar changes would always have Welfare pushed to the final position in the navbar. If you now clear the local storage entry for `$navStore` in your browser, the order will be the intended `Welfare, About`.

We need to decide if the intended behaviour is sensible, and if so, a quick fix would be to create CMS nav entries for all of `News, Welfare, Services, About`. If not, we need some other sensible system for nav ordering.

Is it possible to set the navbar ordering in the CMS?

Ref.
- https://github.com/dowjcr/web-frontend/blob/e50a20fb0c7383df154f3b0d38f9f95b8faac107/src/routes/%2Blayout.svelte#L10-L15
- https://github.com/dowjcr/web-frontend/blob/e50a20fb0c7383df154f3b0d38f9f95b8faac107/src/lib/index.ts#L5-L10

**Comment by GeekPro101** [comment]
@apple-phi Apologies for my delayed reply, I was sunbathing

> Is it possible to set the navbar ordering in the CMS?

Yes - the array order is set.
