### ISSUE TITLE
Table of contents - highlighted link should update as you scroll through page

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#6]

**Comment by apple-phi** [comment]
- This has already been fixed in https://github.com/dowjcr/web-frontend/commit/1ffb1902183969dbcb9899cc9d410bbef5ffa5db
- Note that there is currently insufficient room on the bottom of the page to guarantee that the final page heading will update the ToC `active` state. This can be easily fixed with a footer or similar.
